export const restConstants = {
    GET_CONVERSATIONS_REQUEST: 'GET_CONVERSATIONS_REQUEST',
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    GET_USER_DATA: 'GET_USER_DATA',
    GET_ADVERTS: 'GET_ADVERTS'
};
